//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAWeddingDressAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingRequest
    {
        public BookingRequest()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
        }
    
        public int BR_id { get; set; }
        public int U_id { get; set; }
        public int UserAddressID { get; set; }
        public System.DateTime StartingDate { get; set; }
        public int NoOfDays { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public Nullable<decimal> PenaltyAmount { get; set; }
    
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        public virtual UserAddress UserAddress { get; set; }
        public virtual User User { get; set; }
    }
}
