//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAWeddingDressAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public int BD_id { get; set; }
        public int BR_id { get; set; }
        public int D_id { get; set; }
        public decimal TotalPrice { get; set; }
        public string Feedback { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Size_id { get; set; }
    
        public virtual BookingRequest BookingRequest { get; set; }
        public virtual Dress Dress { get; set; }
    }
}
