//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAWeddingDressAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DressSize
    {
        public int DS_id { get; set; }
        public int D_id { get; set; }
        public int Size_id { get; set; }
        public Nullable<int> Stock { get; set; }
    
        public virtual Dress Dress { get; set; }
        public virtual Size Size { get; set; }
    }
}
