//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAWeddingDressAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dress
    {
        public Dress()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
            this.DressImages = new HashSet<DressImage>();
            this.DressOccasions = new HashSet<DressOccasion>();
            this.DressSizes = new HashSet<DressSize>();
        }
    
        public int D_id { get; set; }
        public int U_id { get; set; }
        public int Category_id { get; set; }
        public int SubCategory_id { get; set; }
        public string Dtitle { get; set; }
        public string Description { get; set; }
        public string Gender { get; set; }
        public decimal RentPrice { get; set; }
        public Nullable<int> AgeYears { get; set; }
        public Nullable<int> AgeMonths { get; set; }
        public Nullable<int> AgeDays { get; set; }
        public Nullable<int> Condition { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
    
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        public virtual DressCategory DressCategory { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<DressImage> DressImages { get; set; }
        public virtual ICollection<DressOccasion> DressOccasions { get; set; }
        public virtual ICollection<DressSize> DressSizes { get; set; }
    }
}
