//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAWeddingDressAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DressCategory
    {
        public DressCategory()
        {
            this.Dresses = new HashSet<Dress>();
            this.SubCategories = new HashSet<SubCategory>();
        }
    
        public int Category_id { get; set; }
        public string Cname { get; set; }
    
        public virtual ICollection<Dress> Dresses { get; set; }
        public virtual ICollection<SubCategory> SubCategories { get; set; }
    }
}
