//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAWeddingDressAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RentAWeddingDressEntities2 : DbContext
    {
        public RentAWeddingDressEntities2()
            : base("name=RentAWeddingDressEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BookingDetail> BookingDetails { get; set; }
        public DbSet<BookingRequest> BookingRequests { get; set; }
        public DbSet<Dress> Dresses { get; set; }
        public DbSet<DressCategory> DressCategories { get; set; }
        public DbSet<DressImage> DressImages { get; set; }
        public DbSet<DressOccasion> DressOccasions { get; set; }
        public DbSet<DressSize> DressSizes { get; set; }
        public DbSet<Size> Sizes { get; set; }
        public DbSet<SubCategory> SubCategories { get; set; }
        public DbSet<UserAddress> UserAddresses { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
