//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAWeddingDressAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Size
    {
        public Size()
        {
            this.DressSizes = new HashSet<DressSize>();
        }
    
        public int Size_id { get; set; }
        public string SizeName { get; set; }
    
        public virtual ICollection<DressSize> DressSizes { get; set; }
    }
}
