//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAWeddingDressAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        public SubCategory()
        {
            this.Dresses = new HashSet<Dress>();
        }
    
        public int SubCategory_id { get; set; }
        public int Category_id { get; set; }
        public string SCname { get; set; }
    
        public virtual ICollection<Dress> Dresses { get; set; }
        public virtual DressCategory DressCategory { get; set; }
    }
}
