//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAWeddingDressAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.BookingRequests = new HashSet<BookingRequest>();
            this.Dresses = new HashSet<Dress>();
            this.UserAddresses = new HashSet<UserAddress>();
        }
    
        public int U_id { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Password { get; set; }
        public Nullable<decimal> CreditBalance { get; set; }
    
        public virtual ICollection<BookingRequest> BookingRequests { get; set; }
        public virtual ICollection<Dress> Dresses { get; set; }
        public virtual ICollection<UserAddress> UserAddresses { get; set; }
    }
}
