//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentAWeddingDressAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddress
    {
        public UserAddress()
        {
            this.BookingRequests = new HashSet<BookingRequest>();
        }
    
        public int UA_id { get; set; }
        public int U_id { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<BookingRequest> BookingRequests { get; set; }
        public virtual User User { get; set; }
    }
}
